# Inputs
samples: ../resources/glue_ps_sampleSheet.txt
chromosomes: ../resources/chromosome_file.txt
ref: /research/projects/trifolium/dovetail/dcg/results/reference_assemblies/haploid_reference/TrR_v6_haploid_reference.fasta 
bams: /node1nfs/archive/projects/GLUE/dnaSeqQC_v2/results/bam 

# Outputs
results_prefix: /scratch/projects/trifolium/glue/glue_ps/results
log_prefix: /scratch/projects/trifolium/glue/glue_ps/logs
